const Images = {
    pet1: require('../assets/images/pet1.png'),
    pet2: require('../assets/images/pet2.png'),
    pet3: require('../assets/images/pet3.png'),
    pet4: require('../assets/images/pet4.png'),
    pet5: require('../assets/images/pet5.png'),
    pet6: require('../assets/images/pet6.png'),
    pet7: require('../assets/images/pet7.png'),
    pet8: require('../assets/images/pet8.png'),
    pet9: require('../assets/images/pet9.png'),
    pet10: require('../assets/images/pet10.png'),
    pet11: require('../assets/images/pet11.png'),
    pet12: require('../assets/images/pet12.png'),
    pet13: require('../assets/images/pet13.png'),
    pet14: require('../assets/images/pet14.png'),
    puppy: require('../assets/images/puppy.png'),
    smalldog: require('../assets/images/smalldog.png'),
    mediumdog: require('../assets/images/mediumdog.png'),
    largedog: require('../assets/images/largedog.png'),
    giantdog: require('../assets/images/giantdog.png'),
    subtype: require('../assets/images/dob.png'),
    others: require('../assets/images/others.png'),
    email:  require('../assets/images/email.png'),
    dob: require('../assets/images/dob.png'),
    question: require('../assets/images/question.png'),
    password: require('../assets/images/password.png'),
    number: require('../assets/images/number.png'),
    petname: require('../assets/images/petname.png'),
    person: require('../assets/images/person.png')
}

export default Images;